# Generated by Django 4.1.1 on 2023-09-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mesaj',
        ),
    ]
