# Generated by Django 4.1.1 on 2023-09-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
