# Generated by Django 4.1.1 on 2023-09-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0008_blogentry_delete_mesaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='edit_permission',
            field=models.BooleanField(default=False),
        ),
    ]
